# Generated by Django 5.0.7 on 2024-07-20 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='residential_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
