EMPLOYEE_ROLES = (
    ('MANAGER', 'MANAGER'),
    ('EMPLOYEE', 'EMPLOYEE'),
    ('ADMINISTRATOR', 'ADMINISTRATOR')
)

EMPLOYMENT_TYPES = (
    ('FULL_TIME', 'FULL_TIME'),
    ('PART_TIME', 'PART_TIME'),
    ('CONTRACT', 'CONTRACT')
)

GENDER_OPTIONS = (
    ('MALE', 'MALE'),
    ('FEMALE', 'FEMALE')
)
