# Generated by Django 5.0.7 on 2024-07-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED'), ('NOT_STARTED', 'NOT_STARTED'), ('CANCELLED', 'CANCELLED'), ('ON_HOLD', 'ON_HOLD')], default='NOT_STARTED', max_length=255),
        ),
    ]
